### PR TITLE
Add support for overriding the publish channel

### PR DESCRIPTION
**Pull request by arturo-seijas**
Add support for overriding the publish channel on the test and publish workflow

### CODE REVIEW

**Comment by gregory-schiano** [comment]
Why do we do that instead of applying the charming-action enforced convention for branch name ?
It feels like we want to do things our own way, which I'm not sure is a good idea... we should unless really good reason use the charming-actions

**Comment by arturo-seijas** [comment]
> Why do we do that instead of applying the charming-action enforced convention for branch name ? It feels like we want to do things our own way, which I'm not sure is a good idea... we should unless really good reason use the charming-actions

That step retrieves `latest/edge` for main and `[track]/edge` for branches matching with `track/*`. Keeping it while allowing overrides will increase complexity and we aren't actually leveraging it

**Review by weiiwang01 — APPROVED** [review]

**Comment by gregory-schiano** [comment]
> > Why do we do that instead of applying the charming-action enforced convention for branch name ? It feels like we want to do things our own way, which I'm not sure is a good idea... we should unless really good reason use the charming-actions
> 
> That step retrieves `latest/edge` for main and `[track]/edge` for branches matching with `track/*`. Keeping it while allowing overrides will increase complexity and we aren't actually leveraging it

Why do we need override then ? I'm worried we would get questions on why we don't use the charming actions and chose our "own way".
I'd rather review the way we work to match other charm engineering teams that going our own way. If we have feedback/constrains that can't match the way other teams are doing, let's discuss on the charming action repo if they can allow "override" for example.

**Comment by arturo-seijas** [comment]
> > > Why do we do that instead of applying the charming-action enforced convention for branch name ? It feels like we want to do things our own way, which I'm not sure is a good idea... we should unless really good reason use the charming-actions
> > 
> > 
> > That step retrieves `latest/edge` for main and `[track]/edge` for branches matching with `track/*`. Keeping it while allowing overrides will increase complexity and we aren't actually leveraging it
> 
> Why do we need override then ? I'm worried we would get questions on why we don't use the charming actions and chose our "own way". I'd rather review the way we work to match other charm engineering teams that going our own way. If we have feedback/constrains that can't match the way other teams are doing, let's discuss on the charming action repo if they can allow "override" for example.

[Here's the current behaviour](https://github.com/canonical/charming-actions/tree/main/channel#branch-selection). In order to fit our use case we'd need to enable overriding the track, which would be the same as not using the action at all.

**Review by yanksyoon — APPROVED** [review]
LGTM!

**Comment by merkata** [comment]
Sorry I'm a bit late for the discussion, but what is our use case?

**Comment by arturo-seijas** [comment]
> Sorry I'm a bit late for the discussion, but what is our use case?

This is the intended behaviour https://github.com/canonical/indico-operator/pull/267. Will be extracting the indico version and publishing to [indico_version]/edge on merge

**Pull request merged**
