### PR TITLE
fix: Remove typo in inputs for chaos

### PR DESCRIPTION
**Pull request by merkata**
Remove a typo (double '$') in the chaos experiment action that causes the passed delay to evaluate to a string such as '$10' - when passed to the action, it evaluates to 0 (due to strconv.Atoi and no error handling) and throws a panic on a division by zero (there is a computation that relies on delay being the divisor). This PR fixes that.

### CODE REVIEW

**Review by nrobinaubertin — CHANGES_REQUESTED** [review]
LGTM

**Review by nrobinaubertin — APPROVED** [review]

**Review by yanksyoon — APPROVED** [review]
LGTM!

**Review by arturo-seijas — CHANGES_REQUESTED** [review]
I noticed the readme is not updated with the new parameters. Would you mind updating it?

**Review by arturo-seijas — APPROVED** [review]
LGTM

**Comment by arturo-seijas** [comment]
> I noticed the readme is not updated with the new parameters. Would you mind updating it?



> I noticed the readme is not updated with the new parameters. Would you mind updating it?

Nvm, it has been updated as part of #70

**Pull request merged**
