### PR TITLE
Add secret arguments to integration tests

### PR DESCRIPTION
**Pull request by yhaliaw**
There is no way to pass secrets to the tox integration test runs.
This PR enables using a secret named `INTEGRATION_TEST_ARGS` as extra arguments.

### CODE REVIEW

**Review by arturo-seijas — COMMENTED** [review]
Can you link a workflow run with the secrets working?

**Comment by amandahla** [comment]
Could you add this new parameter to the README.md file please?

**Comment by yhaliaw** [comment]
> Could you add this new parameter to the README.md file please?

The README is updated.

**Comment by gregory-schiano** [comment]
Does this PR still need some changes ? The changes sounds good to me and has been tested by Niels on Indico

**Comment by yhaliaw** [comment]
This method does not seem to work.

**Review by arturo-seijas — APPROVED** [review]
LGTM

**Review by merkata — APPROVED** [review]

**Comment by merkata** [comment]
> This method does not seem to work.

Can you elaborate?

**Comment by merkata** [comment]
Good addition! I would add this to the README as well, how to make use of secrets in integration tests.

**Pull request merged**
