### PR TITLE
fix Docker lint for multiple Dockerfiles

### PR DESCRIPTION
**Pull request by amandahla**
**Problem**:
```
##[debug]Set output found = ./indico.Dockerfile
Error: Unable to process file command 'output' successfully.
Error: Invalid format './indico-nginx.Dockerfile'
```
https://github.com/canonical/indico-operator/actions/runs/3704072925/jobs/6276262775

**Proposal**:
Change run to not print new lines.
```
run: echo -n "found=$(find . -name "*Dockerfile" -printf "%p ")" >> $GITHUB_OUTPUT
```

### CODE REVIEW

**Review by arturo-seijas — DISMISSED** [review]
LGTM. Can you link a test run?

**Review by arturo-seijas — APPROVED** [review]
LGTM

**Comment by amandahla** [comment]
> LGTM. Can you link a test run?

Ran one in this fork:
https://github.com/amandahla/indico-operator/actions/runs/3705119676/jobs/6278607023

**Review by gregory-schiano — APPROVED** [review]
LGTM

**Comment by jdkandersson** [comment]
It failed because the `working-directory` was removed, please don't merge anything with failed checks, we need to fix them!

**Comment by jdkandersson** [comment]
Fixed the issue here: #61

**Pull request merged**
