### PR TITLE
Fix secrets passing on reusable workflows

### PR DESCRIPTION
**Pull request by arturo-seijas**
Fix secrets not being properly passed for reusable workflows. This is currently causing the publish workflow to fail on the integration test step.

### CODE REVIEW

**Review by mthaddon — DISMISSED** [review]
LGTM, thx

**Review by weiiwang01 — DISMISSED** [review]

**Review by gtrkiller — DISMISSED** [review]
LGTM

**Review by mthaddon — DISMISSED** [review]
LGTM

**Review by mthaddon — DISMISSED** [review]
LGTM

**Review by gtrkiller — DISMISSED** [review]
LGTM

**Review by weiiwang01 — DISMISSED** [review]

**Review by gtrkiller — APPROVED** [review]
LGTM

**Review by mthaddon — APPROVED** [review]
LGTM

**Pull request merged**
