### PR TITLE
Do not pack the charm if the metadata file is not present

### PR DESCRIPTION
**Pull request by arturo-seijas**
Do not pack the charm if the metadata file is not present to support repositories not containing charms

### CODE REVIEW

**Comment by gregory-schiano** [comment]
Important note ! Relying on metadata.yaml presence is a bad move since we're merging metadata and config into charmcraft.yaml, therefore metadata.yaml will become optional !

**Comment by arturo-seijas** [comment]
> Important note ! Relying on metadata.yaml presence is a bad move since we're merging metadata and config into charmcraft.yaml, therefore metadata.yaml will become optional !

Thanks for the heads up. We'll have to support both formats, but there are already a lot of places where the metadata info is parsed, so it will require a significant work

**Review by jdkandersson — DISMISSED** [review]

**Review by gtrkiller — DISMISSED** [review]
LGTM

**Review by jdkandersson — APPROVED** [review]

**Review by mthaddon — APPROVED** [review]
LGTM

**Pull request merged**
